---
title: "SWATH data analysis with xcms"
package: xcms
output:
  BiocStyle::html_document:
    toc_float: true
vignette: >
  %\VignetteIndexEntry{SWATH data analysis with xcms}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{xcms,RColorBrewer,faahKO,pander,magrittr,BiocStyle,pheatmap}
  %\VignettePackage{xcms}
  %\VignetteKeywords{mass spectrometry, metabolomics}
bibliography: references.bib
csl: biomed-central.csl
references:
- id: dummy
  title: no title
  author:
  - family: noname
    given: noname
---

```{r biocstyle, echo = FALSE, results = "asis" }
BiocStyle::markdown()
```

**Package**: `r Biocpkg("xcms")`<br />
**Authors**: Johannes Rainer, Michael Wittingen<br />
**Modified**: `r file.info("swath.Rmd")$mtime`<br />
**Compiled**: `r date()`

```{r init, message = FALSE, echo = FALSE, results = "hide" }
## Silently loading all packages
library(BiocStyle)
library(xcms)
library(pander)
register(SerialParam())
```

# Introduction


# Data import

```{r load-swath data}
library(xcms)

fl <- "/Users/jo/Projects/git/michaelwitting/metabolomics2018/data/PestMix1_SWATH.mzML"
swth <- readMSData(fl, mode = "onDisk")

```

```{r playground}
table(msLevel(swth))

head(fData(swth))


res <- writeMSData(swth, file = "/Users/jo/Desktop/test.mzML")
tmp <- readMSData("/Users/jo/Desktop/test.mzML", mode = "onDisk")

library(testthat)
expect_equal(fData(tmp), fData(swth))
```
