setClass("xcmsSet", representation(peaks = "matrix", groups = "matrix",
                                   groupidx = "list",
                                   filled="numeric",
                                   phenoData = "data.frame",
                                   rt = "list",
                                   filepaths = "character", profinfo = "list", dataCorrection="numeric",
                                   polarity = "character", progressInfo = "list", progressCallback="function"),
         prototype(peaks = matrix(nrow = 0, ncol = 0),
                   groups = matrix(nrow = 0, ncol = 0),
                   groupidx = list(),
                   filled = integer(0),
                   phenoData = data.frame(), rt = list(),
                   rt = list(),
                   filepaths = character(0), profinfo = vector("list"), dataCorrection=integer(0),
                   polarity = character(0), progressInfo = list(), progressCallback= function(progress) NULL))
